# translational
kp_x: 0.7
kp_y: 0.7
kp_z: 800.
#-----
ki_x: 0
ki_y: 0
ki_z: 0.
#-----
kd_x: 0.2
kd_y: 0.2
kd_z: 200.
#-----

# rotational
kp_phi: 5
kp_theta: 5
kp_psi: 7
#-----
ki_phi: 0.
ki_theta: 0.
ki_psi: 0.
#-----
kd_p: 0.4
kd_q: 0.4
kd_r: 5
